### ISSUE TITLE
I can turn on devices but not off.  

### ISSUE THREAD

**Issue by rickgartner** [rodtoll/homebridge-isy-js#39] opened 2016-10-11 02:00 UTC
I'm having a problem turning devices off and on.  I can turn them on, but never off.  I'm using an isy 994 with firmware 4.51 I have built out a PI system as well as a VM running ubuntu and get the same results.
I get the Ignoring redundant power state when I turn the device off.  It's doesn't seem to matter if I wait a couple of seconds or 30 minutes before issuing the off command.  Always get the same message in the logs.

[10/9/2016, 3:52:37 PM] [isy-js] 116-9-0#15:52:37- LIGHT: Living Room Light Setting powerstate to 0
[10/9/2016, 3:52:37 PM] [isy-js] 116-9-0#15:52:37- LIGHT: Living Room Light Ignoring redundant setPowerState

**Comment by rodtoll** [comment] 2016-10-16 17:37
When devices turn on but not off it means that the homebridge plug in is not being updated when the state changes on the ISY. This is usually because of a firmware bug -- updating to latest firmware addresses this or you have too many devices and programs on your network already getting status updates from your ISY. The ISY can only send change notifications to a limited number of clients at a time so if this is maximum is exceeded Homebridge-isy won't see state changes.

**Comment by rodtoll** [comment] 2016-10-16 18:16
Closing this is a duplicate of issue #32

**Closed as completed by rodtoll** 2016-10-16 18:16 UTC
